### PR TITLE
Update spacy dependency version

### PR DESCRIPTION
**Pull request by MichalMalyska**
If we can get this done + release then scispacy=0.5.0 would be compatible with medspacy which it currently is not. Passes all tests so there shouldn't be any issues

### CODE REVIEW

**Comment by dakinggg** [comment]
I'm not at the Allen institute anymore, so this might move pretty slowly. But the other thing that would need to be done is check whether the models need to be retrained. I guess to check this you would need to run the model evaluations in project.yml and make sure the metrics are the same for at least the small model or something, on spacy 3.1 and spacy 3.2

**Comment by dakinggg** [comment]
I should also note that if you urgently need this for your workflow, you can make the change and build scispacy from source

**Comment by qhreul** [comment]
@dakinggg Does that mean that the SciSpacy is no longer managed under the Allen Institute?

**Comment by dakinggg** [comment]
It means the package is very lightly maintained right now.

**Comment by dakinggg** [comment]
Closing because I am retraining the models for spacy 3.2

**Pull request closed without merging**
