### PR TITLE
encoding="utf-8"

### PR DESCRIPTION
**Pull request by jgroehm**
Thanks for the amazing library! 

Hit the following error using export_umls_json.py with UMLS 2022AA:
'charmap' codec can't decode byte 0x81 in position X: character maps to <undefined>

Resolved by adding the utf-8 encoding throughout umls_utils.

### CODE REVIEW

**Review by dakinggg — APPROVED** [review]
Thanks @jgroehm LGTM! The CI is failing because we format all files with `black`. If you reformat the file with `black candidate_generation.py --line-length 88`, it should be good to go.

**Comment by dakinggg** [comment]
@jgroehm The black commit doesn't look right. It doesn't contain any reformatting, just a stray space added. Can you try again?
Command should be `black candidate_generation.py --line-length 88` and then add and commit that change.

**Comment by jgroehm** [comment]
Sorry for the false start there, new to black, must not have set up the VSCode extension correctly. CLI appears to have done the trick. Thank you!

**Comment by dakinggg** [comment]
Hey @jgroehm, sorry I forgot about this. Merging now, thanks!

**Pull request merged**
